<div class="ajaxcart">
	<ul class="items">
		<?php foreach ($this->getItems() as $_item): ?>
			<?php echo $this->getItemHtml($_item) ?>
		<?php endforeach; ?>
	</ul>
	<div class="cart-actions">
		<ul class="checkout-types">
			<li>
				<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/url')->getCartUrl() ?>')"><span><span><?php echo $this->__('View Shopping Cart') ?></span></span></button>
			</li>
			<?php if (! $this->hasError()): ?>
				<?php foreach ($this->getMethods('methods') as $method): ?>
					<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
						<li><?php echo $methodHtml; ?></li>
					<?php endif; ?>
				<?php endforeach; ?>
			<?php endif; ?>
		</ul>
	</div>
</div>
